// Code generated using `yarn codegen`, DO NOT EDIT.
//
// no really though, do not edit this file.
// noinspection JSUnusedGlobalSymbols

import * as Types from '../types.d';

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
import gql from 'graphql-tag';
export type GetPostPerformanceStatsQueryVariables = Types.Exact<{
    id: Types.Scalars['ID']['input'];
}>;

export type GetPostPerformanceStatsQuery = {
    __typename?: 'Query';
    performance?: {
        __typename?: 'Performance';
        id: string;
        duration: number;
        song: { __typename?: 'Song'; id: string; title: string };
        author?: { __typename?: 'User'; id: string; name?: string | null } | null;
        notes: Array<{ __typename?: 'PerformanceNote'; at: number; precision: number }>;
    } | null;
};

export declare const GetPostPerformanceStats: import('graphql').DocumentNode;

export const GetPostPerformanceStatsDocument = /*#__PURE__*/ gql`
    query GetPostPerformanceStats($id: ID!) {
        performance(id: $id) {
            id
            song {
                id
                title
            }
            author {
                id
                name
            }
            duration
            notes {
                at
                precision
            }
        }
    }
` as unknown as DocumentNode<GetPostPerformanceStatsQuery, GetPostPerformanceStatsQueryVariables>;
