// Code generated using `yarn codegen`, DO NOT EDIT.
//
// no really though, do not edit this file.
// noinspection JSUnusedGlobalSymbols

import * as Types from '../types.d';

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
import gql from 'graphql-tag';
export type GetVirtuozPlayVersionQueryVariables = Types.Exact<{ [key: string]: never }>;

export type GetVirtuozPlayVersionQuery = {
    __typename?: 'Query';
    virtuozPlay: { __typename?: 'VirtuozPlay'; version: string };
};

export declare const GetVirtuozPlayVersion: import('graphql').DocumentNode;

export const GetVirtuozPlayVersionDocument = /*#__PURE__*/ gql`
    query GetVirtuozPlayVersion {
        virtuozPlay {
            version
        }
    }
` as unknown as DocumentNode<GetVirtuozPlayVersionQuery, GetVirtuozPlayVersionQueryVariables>;
