import type { CodegenConfig } from '@graphql-codegen/cli';

const config: CodegenConfig = {
    overwrite: true,
    schema: '../graph/schema.graphqls',
    documents: ['./gql/queries/**/*.graphql'],
    hooks: {
        afterAllFileWrite: ['prettier --write'],
    },
    generates: {
        './gql/types.d.ts': {
            plugins: ['add', 'typescript'],
            config: {
                constEnums: true,
                enumsAsConst: true,
                enumsAsTypes: true,
                immutableTypes: true,
                useImplementingTypes: true,
                content: [
                    '// Code generated using `yarn codegen`, DO NOT EDIT.',
                    '//',
                    '// no really though, do not edit this file.',
                    '// noinspection JSUnusedGlobalSymbols\n',
                ],
            },
        },
        './gql/': {
            preset: 'near-operation-file',
            presetConfig: {
                baseTypesPath: 'types.d.ts',
                extension: '.ts',
            },
            plugins: ['add', 'typescript-operations', 'typed-document-node'],
            config: {
                pureMagicComment: true,
                documentMode: 'graphQLTag',
                importDocumentNodeExternallyFrom: 'near-operation-file',
                addOperationExport: true,
                withCompositionFunctions: false,
                content: [
                    '// Code generated using `yarn codegen`, DO NOT EDIT.',
                    '//',
                    '// no really though, do not edit this file.',
                    '// noinspection JSUnusedGlobalSymbols\n',
                ],
            },
        },
        './graphql.schema.json': {
            plugins: ['introspection'],
        },
    },
};

export default config;
